/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kz.zhanbolat.files;



public class App {

    // run the test cases in class AppTest
    public static void main(String[] args) {

    }
}
