/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kz.zhanbolat.files;

public class App {

    public static void main(String[] args) {
        if (args.length < 2) {
            throw new IllegalArgumentException("Usage: <from> <to>");
        }

        FastFileMover fastFileMover = new FastFileMoverFileChannel();
        fastFileMover.moveFile(args[0], args[1]);
    }
}
