/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kz.zhanbolat.files;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class App {
    private static final Logger logger = LogManager.getLogger(App.class);

    public static void main(String[] args) {
        if (args.length < 2) {
            throw new IllegalArgumentException("Usage: <from> <to>");
        }
        long startTime = System.currentTimeMillis();
        FastFileMover fastFileMover = new FastFileMoverNewerNIO();
        fastFileMover.moveFile(args[0], args[1]);
        long endTime = System.currentTimeMillis();
        logger.info("Execution time: " + (endTime - startTime) + " millisecond");
    }
}
